//
//  MAVRadio.h
//  MCHP MFI
//
//  Created by BRYAN GALUSHA on 1/17/13.
//  Copyright (c) 2013 Microchip Technology. All rights reserved.
//

#import "MAVMessage.h"

@interface MAVRadio : MAVMessage
/*
//This is extracted from SiK firmware here:
https://github.com/tridge/SiK/blob/master/Firmware/radio/mavlink.c
 
 
we use a hand-crafted MAVLink packet based on the following
message definition

<message name="RADIO" id="166">
<description>Status generated by radio</description>
<field type="uint8_t" name="rssi">local signal strength</field>
<field type="uint8_t" name="remrssi">remote signal strength</field>
<field type="uint8_t" name="txbuf">percentage free space in transmit buffer</field>
<field type="uint8_t" name="noise">background noise level</field>
<field type="uint8_t" name="remnoise">remote background noise level</field>
<field type="uint16_t" name="rxerrors">receive errors</field>
<field type="uint16_t" name="fixed">count of error corrected packets</field>
</message>
*/

@end
